### ISSUE TITLE
Feature Request - Force Inline *All*

### ISSUE THREAD

**Issue by Roadspill** [mattberkowitz/autoclose-html#110]
Do you have plans to have a Force Inline *All* option[checkbox], with the ability to adjust just the Force Block section?

I find the spacing to be frustrating at times, where I'm having to delete a lot of un-needed spaces and new lines.

Thanks for taking a look at this.

**Comment by charlieclark** [comment]
I agree with this! I uninstalled the plugin because I don't want newlines to be forced on me. Would love to still be able to use the auto close functionality though.

**Comment by mattberkowitz** [comment]
With 0.20.0 you can use "*" for the Force Inline option to accomplish this.

**Comment by Roadspill** [comment]
Tried this, it didn't work.

**Comment by mattberkowitz** [comment]
Can you send me paste in config file (Atom Menu > Open Your Config File). Also confirm you updated to autoclose-html 0.20.0 which you can see in Preferences, Packages tab. You shouldn't need to restart atom, but give that a try as well.
