### ISSUE TITLE
Auto-close Settings have missing text

### ISSUE THREAD

**Issue by stuartlangridge** [mattberkowitz/autoclose-html#111]
![atom-no-close](https://cloud.githubusercontent.com/assets/4356350/12440054/89af22d0-beec-11e5-88a5-7576c4106732.png)

I suspect that the code contains unescaped HTML which therefore isn't being shown in the Settings panel.

**Comment by mattberkowitz** [comment]
Thanks, I'll fix this in the next release which is coming shortly
