### ISSUE TITLE
Using autoclose html on a different extension

### ISSUE THREAD

**Issue by PierreCavalet** [mattberkowitz/autoclose-html#112]
Would it be possible to use autoclose-html on a something.html.twig file ? I'm just talking about using the default HTML behavior, not about a full twig support.

**Comment by mattberkowitz** [comment]
I'm not sure what twig is, so I can't comment on that. What you need to do is add the correct grammar. To the Additional Grammars setting. The grammar name can be found in the bottom right corner of the atom window when a file is open. ("CoffeeScript" in the first picture here https://atom.io/docs/v1.4.0/using-atom-grammar)

**Comment by PierreCavalet** [comment]
Nice, it's working. Thank you!
