### ISSUE TITLE
Autoclose generates closing tag duplicates

### ISSUE THREAD

**Issue by designarti** [mattberkowitz/autoclose-html#113]
It happened after the last update which I have made today.
This is what happens after closing DIV. Same happened with the body element and the html element before that.
```
        <div>
        

        </div>
        </div>
```

**Comment by mattberkowitz** [comment]
It happens after every update. Basically when the plugin updates it rebinds the events. I put a fix in for this update, however because of the way the bug happens it won't do it's thing until *next* update.

Just close and reopen atom to get rid of it

**Comment by designarti** [comment]
Yes, that has done it. Thanks!
