### ISSUE TITLE
Double Autoclose

### ISSUE THREAD

**Issue by ruxiang05** [mattberkowitz/autoclose-html#114]
In your last update the closing tag is generated twice.

**Comment by AbryceT** [comment]
Hey Matt,

Getting the same error as ruxiang05

**Comment by mattberkowitz** [comment]
It happens after every update. Basically when the plugin updates it rebinds the events. I put a fix in for this update, however because the fix requires something to fire when the plugin unregisters it won't do it's thing until next update.

Just close and reopen atom to get rid of it
