### ISSUE TITLE
Div tag inserts 2 new rows plus double closing tag

### ISSUE THREAD

**Issue by vladetd** [mattberkowitz/autoclose-html#115]
Screenshot : http://prntscr.com/9uk9ta

**Comment by Krzysiu-lifeinmobile** [comment]
I have this same problem.
Today I update plugin to 0.20.0 version.

**Comment by mattberkowitz** [comment]
It happens after every update. Basically when the plugin updates it rebinds the events. I put a fix in for this update, however because the fix requires something to fire when the plugin unregisters it won't do it's thing until *next* update.

Just close and reopen atom to get rid of it
