### ISSUE TITLE
!!PLEASE READ BEFORE POSTING ABOUT DOUBLE CLOSING TAGS!!

### ISSUE THREAD

**Issue by mattberkowitz** [mattberkowitz/autoclose-html#117]
It happens after every update. Basically when the plugin updates it rebinds the events. I put a fix in with 0.20.0, however because the fix requires something to fire when the plugin unregisters it won't do it's thing until *next* update.

Just close and reopen atom to get rid of it.

**Comment by muffinmad** [comment]
As for version 0.20.0 additional closing tag will be appended for each grammar change.

**Comment by mattberkowitz** [comment]
Thanks, I think it should be an easy fix, I'll try and publish another version with that fix in the next few days

**Comment by Smudded** [comment]
This is happening to me even after closing and reopening Atom. When I reopen Atom it's fine for a bit, but then eventually it will start double-closing tags again.

**Comment by mattberkowitz** [comment]
@Smudded Is it possible you have a file open in multiple tabs or multiple instances of atom or something like that? Do you manually change the grammar?

**Comment by Smudded** [comment]
Oh, I completely missed muffinmad's comment about that. I do manually change the grammar every now and then. Thanks Matt!

**Comment by atd** [comment]
Disabiing and enabling the package again also worked for me

**Comment by mrmaddotta** [comment]
Hi Guys

Does the latest release fix this issue when editing multiple lines (I'm still experiencing the weirdness, wondering if its my install or something whack like that)? 

I have disabled/enabled package, quit/open..

Thanks

![doubletag](https://cloud.githubusercontent.com/assets/5221691/13113855/9c6c97fe-d599-11e5-9e5c-f37451dd110e.gif)

**Comment by mattberkowitz** [comment]
@mrmaddotta No, the latest update made no changes to the multiple cursor issue, it's still broken
