### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sollymay** [mattberkowitz/autoclose-html#119]
Hi Guys,

It would be awesome that you could use this with HTML (Django)

I use Django a lot but this will not autoclose my opening tags in django based HTML.

Could you please implement it?

I would really appreciate it.

**Comment by mattberkowitz** [comment]
You can add "HTML (Django)" to the additional grammars option, and it will work. I can add it to the default list when I'm doing another release

**Comment by mattberkowitz** [comment]
0.22.0 should get rid of the need to define grammars
