### ISSUE TITLE
Feature Request: Line break on/off switch in settings.

### ISSUE THREAD

**Issue by colonelpopcorn** [mattberkowitz/autoclose-html#120]
Really like this plugin but would like to be able to auto-close HTML without inserting a line break. Consider allowing a toggle with a hotkey for line breaks. I'll see if I can make this happen.

Edit: Just realized this functionality is already included, but there is no hotkey to toggle all on one line/all off one line. Hotkeys!

**Comment by mattberkowitz** [comment]
I'm targeting 0.23.0 for this (hopefully will come in a week or so), once the dust settles on 0.22.0.

My plan is to have cmd/ctrl + > force inline or block (with an option to choose which)
and alt + cmd/ctrl + > to force the other

**Comment by colonelpopcorn** [comment]
I'm no longer using this package.
