### ISSUE TITLE
Closing tags are doubling

### ISSUE THREAD

**Issue by sunabozu** [mattberkowitz/autoclose-html#124]
The gif should be self-explanatory.
![twxc5fynhj](https://cloud.githubusercontent.com/assets/135717/13113081/452c3f88-d596-11e5-8918-76ffb5ef2135.gif)

This bug reproduces regardless a type of a document (I checked html, vue) and a chosen tag.

Atom 1.5.3 with latest packages, OS X.

**Comment by DennisNygren** [comment]
Experiencing the same issue after the latest update.

**Comment by mattberkowitz** [comment]
Were you at 0.20.0 (released a few weeks ago) prior to upgrading or a version older than that?  Regardless, closing atom and reopening should stop it. 0.20.0 should have fixed this going forward.
