### ISSUE TITLE
Feature requiest: Turn off auto new line when autoclosing

### ISSUE THREAD

**Issue by ludberg** [mattberkowitz/autoclose-html#125]
It would be nice to be able to turn off the feature so that entering a div-tag will not yield

`<div>`
..
`</div>`

but rather 

`<div></div>`

It takes less time to hit Enter one more time and then Ctrl+Shift+I to auto-indent than it takes to remove those extra New Lines. 

A good alternative would be if Ctrl+Z after autocomplete only remove the New Lines.

**Comment by mattberkowitz** [comment]
You can use the Force Inline option for this
