### ISSUE TITLE
Closing html does not produce closing tag

### ISSUE THREAD

**Issue by PD75** [mattberkowitz/autoclose-html#129]
Hi,

Autoclose is not working at all for me now. When i type '>' nothing happens at all.

Win 10
Atom 1.5.3
autoclose-html 0.22.0

I have reverted to 0.21.0 and it works again.

Br

Paul

**Comment by pythogician** [comment]
Hey,

same problem on Ubuntu 15.10, Atom 1.2.4. Also had to downgrade to 0.21.0 version.

pythogician

**Comment by mattberkowitz** [comment]
@PD75 @pythogician Do either of you use non-US / non-QUERTY keyboards? If so it may be related to #128 

I weighing the options, but might have to back out of the changes I made in 0.22.0

**Comment by PD75** [comment]
@mattberkowitz yes using swedish keyboard. Will test US tomorrow to see if problem persists.

**Comment by pythogician** [comment]
@mattberkowitz non-US keyboard. Apparently it's related to #128 as you mentioned.

**Comment by PD75** [comment]
@mattberkowitz I can confirm that it works on US for me but not Swedish, so related to #128

**Comment by mattberkowitz** [comment]
I'm going to close this issue, I'm working out the best way to address this problem (ideally temporarily until the atom team introduces internal fixes for international keyboards). Hopefully I can come up with something acceptable and have it released later this week, sorry for the inconvenience
