### ISSUE TITLE
Cannot type ">" character in PHP or HTML files.

### ISSUE THREAD

**Issue by laxeot** [mattberkowitz/autoclose-html#130]
I'm not sure if this applies to other types of files (it seemed to work in Javascript files) but it appears to not want to autoclose in PHP or HTML files, and I cannot type a ">" character. What I'm currently doing is having it on my clipboard so I can easily paste it.

**Comment by mattberkowitz** [comment]
Many users of non-QWERTY or non-US keyboards are having a problem where the keybinding attached to ">" is actually bound to some other key (see #128), is it possible this is your problem as well?

When you press ">" what happens? Does it output a ">", but doesn't add the closing tag or does it do nothing?

**Comment by laxeot** [comment]
I AM using a US QWERTY keyboard, so I doubt this is the issue.

Nothing happens. The character does not appear, and the tag does not close.

**Comment by mattberkowitz** [comment]
If you press cmd/ctrl + . to open up the keybinding resolver, does it show the "autoclose-html:close-and-complete" resolving when you press ">" in an html/php file?

**Comment by laxeot** [comment]
It does, yes.

**Comment by mattberkowitz** [comment]
The very first line of code in the command is

```
atom.workspace.getActiveTextEditor().insertText(">")
```

so I'm not sure what could be causing it from, at the very least, inserting the ">".

Could you give me some more info on what OS, version of atom, and community packages you have installed?  I can try and replicate the issue on my end.

If you're comfortable debugging, with view > developer > toggle developer tools, you should be able to set breakpoints like you would in the normal chrome developer tools.

**Comment by tetsuo808** [comment]
I can confirm this issue too, can't type ">". It started happening as soon as I upgrade the latest (0.22.0) version. I've had to disable the package for now.

**Comment by laxeot** [comment]
So, it started working all of the sudden? Everything is happening as expected. I'll still give you the details, though:
I'm using Windows 10, Atom 1.5.3, and have the following community packages installed:

- atom-beautify
- autoclose-html (obviously :stuck_out_tongue_winking_eye:)
- color-picker
- javascript-snippets
- linter
- minimap
- php-cs-fixer

**Comment by mattberkowitz** [comment]
@laxeot Did you restart atom perhaps?

**Comment by laxeot** [comment]
I did restart atom, yes.

**Comment by mattberkowitz** [comment]
@tetsuo808 Does restarting atom fix the issue for you too? If so I'll close this

**Comment by tetsuo808** [comment]
@mattberkowitz Indeed it does :+1:
