### ISSUE TITLE
Double greater than

### ISSUE THREAD

**Issue by jalexanderconsulting** [mattberkowitz/autoclose-html#131]
In the latest update (0.23.0) I noticed whenever I type a greater than ">" it puts two ">>". The is really annoying when you are using class->method calls when you have to remove a > everytime.

Thanks.

**Comment by iamsankalp** [comment]
facing the same.

**Comment by mattberkowitz** [comment]
@jalexanderconsulting @iamsankalp If you exit atom and reopen it, does the problem still manifest? If so, can you please provide me as much additional context as possible: other community plugins, os, atom version etc. so I can try to reproduce

**Comment by mattberkowitz** [comment]
I was able to reproduce this by installing 0.22.0 and upgrading 0.23.0. It was fixed after closing and reopening atom
