### ISSUE TITLE
double greater when dot typed in php string

### ISSUE THREAD

**Issue by evwni** [mattberkowitz/autoclose-html#132]
Hi
in lastest (since 2 or 3 versions) dot is replaced by one greater or two greater sign
(azerty keyboard layout)

**Comment by mattberkowitz** [comment]
see #128

**Comment by evwni** [comment]
thanks, works fine


Le 02/03/2016 18:10, mattberkowitz a écrit :
>
> Closed #132 <https://github.com/mattberkowitz/autoclose-html/issues/132>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mattberkowitz/autoclose-html/issues/132#event-574976537>.
>


-- 
Cordialement

Eric Verbaere
Win Novation
