### ISSUE TITLE
Legacy mode and problems since 0.22.0 and 0.23.0

### ISSUE THREAD

**Issue by emileber** [mattberkowitz/autoclose-html#133]
After updating, I found out that the tags were not auto-closing, so I checked and found about the legacy mode for international keyboard layouts. 

I have a standard English keyboard with a Canadian french layout mostly to help with accented characters and I'm just used to it. Other than that, it's a standard qwerty.

So while searching for a solution, I found out that the key that register the events for me is `shift-dotKey` which has a `>` on it. But my layout, I need to type a `|` normally to get the `>`. I changed my user keybinding file accordingly and it now auto-closes but it also add an extra `>` which is annoying.

For now, I think I'm just going to revert to ~~0.22.0~~ Edit: doesn't work, I needed to revert back to 0.21.0

**Comment by mattberkowitz** [comment]
Legacy/International mode disables the keybindings (or rather exits them before they execute anything) and instead users the old method of watching the buffer event for ">" 

I've gotten some reports about an extra ">" but no ones given any context so I can't effectively debug it. Can you first try restarting atom and see if that solves the problem?

**Comment by emileber** [comment]
Ok, after reading your comment, I checked the source and saw that there was an explicit option for the legacy mode which I never saw when trying to debug my problem initially. So I updated back to 0.23.0 and restarted Atom and it worked out of the box, without the legacy mode.

So I will close this. Thanks for your time and sorry for the misleading issue!
