### ISSUE TITLE
recent update is bad

### ISSUE THREAD

**Issue by beeseenmedia** [mattberkowitz/autoclose-html#135]
the keystroke > on a php file makes it type >>

on an html file if you type 
`<div>`
the result is the following
```
<div>
	>
</div>
```

**Comment by mattberkowitz** [comment]
Restart atom. Not sure why it's doing it twice (I'd assume the internal keybinding stuff would stop it from binding twice) but a restart will fix it

**Comment by beeseenmedia** [comment]
thats probably true.  i didnt think that could be it since it also did it on the php file but i can see how that can happen.
