### ISSUE TITLE
Workaround for removed feature: additional grammars

### ISSUE THREAD

**Issue by Tapped** [mattberkowitz/autoclose-html#136]
Commit https://github.com/mattberkowitz/autoclose-html/commit/73cdb1292978c3b491ef5adc24bb108001aebce3 removed the additional grammars feature. However this feature was used for our language _UX_. Can I somehow set a setting in our grammar, so that your plugin still works with our language again? (https://github.com/fusetools/Fuse.AtomPlugin/blob/master/grammars/ux.cson)

**Comment by mattberkowitz** [comment]
The new method of detecting "grammar" is to keybind to ">" in text editors with data-grammar that contains "html". I believe the data-grammar attribute is driven by the scopeName of the grammar.

If you go to Atom Preferences > Keybindings, there is a link at the top "your keymap file". Click that and try adding:

```
'atom-text-editor[data-grammar~="ux"]':
	'>': 'autoclose-html:close-and-complete'
```

to your keymap file

**Comment by Tapped** [comment]
Thank you for getting back to me, and for sharing a solution. I am gonna share my experience after some tests, but I am closing this ticket for now.
