### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by michaelpittino** [mattberkowitz/autoclose-html#137]
I installed it but it doesn't work at all.
When I open a tag like `<div>` nothing happens.

**Comment by mattberkowitz** [comment]
I will need some additional context (is this a clean install or upgrade? settings? os? other plugins? etc). If you use a non-US or non-QUERTY keyboard then it's most likely related to #128.

**Comment by michaelpittino** [comment]
Oh it's #128. Thanks
