### ISSUE TITLE
Impossible to write ':' character

### ISSUE THREAD

**Issue by Adagal** [mattberkowitz/autoclose-html#138]
After the installation of the plugin I cannot write ':' character.

**Comment by mattberkowitz** [comment]
I'm guessing you're on a non-US or non-QUERTY keyboard, see #128 if so, otherwise can you provide additional context (settings, other plugins, os, etc)

**Comment by Adagal** [comment]
Sure, I am spanish with spanish keyboard.

**Comment by mattberkowitz** [comment]
Your best bet for now is to check the "Legacy/International Mode" checkbox in preferences, until the deeper issues with atom have been worked out
