### ISSUE TITLE
Autoclose HTML replace the key ':' by '>'

### ISSUE THREAD

**Issue by mrsoto** [mattberkowitz/autoclose-html#144]
Having this package enabled each time I do type colon ':' it is replaced by gather than '>'

Environment: Linux mint 17.3 (Ubuntu 14)

Keyboard: Spanish

**Comment by hisorange** [comment]
Same issue in hungarian keymap.

**Comment by mattberkowitz** [comment]
Please use the "Legacy/International Mode" option see #128
