### ISSUE TITLE
autoclose closes self-closing tags twice

### ISSUE THREAD

**Issue by rnyberg** [mattberkowitz/autoclose-html#152]
Typing `<some:tag/>` turns into

```
<some:tag/>

</some:tag/>		
```

This used to work some versions ago.

**Comment by joshaidan** [comment]
I've noticed this too typing <br/>, which becomes:

<br/>

</br/>

For what it's worth, I also noticed if you disabled, then enable the package without restarting Atom, it does this:

<br/>
>
</br/>

If I have time, I'll try to look through the code and see if I can figure this out.

**Comment by joshaidan** [comment]
A quick workaround is to add `br/` to your "Never Close Elements" list.

**Comment by rnyberg** [comment]
It's not a quick workaround when the in-house language consists of many dozens of tags that are either self-closed or open with parameter tags in between. This plugin used to be able to distinguish between the two if I typed `<tag>` or `<tag/>` but nowadays it always makes an end tag.

Could you share an earlier version of the plugin that everyone affected could use meanwhile?

**Comment by joshaidan** [comment]
I submitted PR #157 which should fix the problem for all tags. When it's searching for the element in @neverClose, it's including the forward slash. My PR strips the forward flash. This may not be the best fix--I imagine you might be able to fix it by examining the regex, but this fixes the problem for all tags.

**Comment by mattberkowitz** [comment]
This should be resolved with 0.24
