### ISSUE TITLE
atom windows seems to close tag twice..

### ISSUE THREAD

**Issue by bryanlynn** [mattberkowitz/autoclose-html#16]

**Comment by hsoto92** [comment]
For some reason, this started happening to me today after an update rolled precisely today also. Any ideas what might be causing this?

**Comment by hsoto92** [comment]
![double tag](https://cloud.githubusercontent.com/assets/6208570/7656858/974f7898-faea-11e4-8515-bee0a7a26181.png)
Here's an example of it
