### ISSUE TITLE
Package overrides : symbol on Icelandic keyboards

### ISSUE THREAD

**Issue by lightspeed1001** [mattberkowitz/autoclose-html#163]
Pressing shift+. on Icelandic keyboards results in a '>', instead of ':' ,  and triggers the autocomplete function.
Pressing shift+< results in a '>' as expected, but no autocomplete.

**Comment by IsoLinearCHiP** [comment]
I have the same issue on a german keyboard. Thankfully I found this post: https://discuss.atom.io/t/colon-is-not-working-when-coding/26836/6 suggesting autoclose-html might be causing the issue.

After unchecking the "Enable" in the keybindings section of autoclose-html the issue was resolved.

**Comment by lightspeed1001** [comment]
Duplicate issue, closing.
