### ISSUE TITLE
Feature Request: Keybinding to prevent creation of close tag

### ISSUE THREAD

**Issue by pdxwolfy** [mattberkowitz/autoclose-html#166]
I frequently want to insert an open tag somewhere in my HTML, and then later choose where I want to close tag. Is there (or could there be) a way for a simple keybinding to prevent the automatic creation of the close tag? Say, something like Option-> to just generate the '>' but not the </tag> part?  Thanks.

**Comment by benlind** [comment]
I achieved this by creating a custom function for inserting a plain `>` like so:

1. Add this to your `init.coffee`:
```
atom.commands.add 'atom-text-editor',
  # Inserts a closing angle bracket '>' without triggering autoclose-html
  'custom:insert-plain-closing-angle': ->
    atom.workspace.getActiveTextEditor()?.insertText('>')
```
2. Add this to your `keymap.cson`:
```
'atom-text-editor':
  'alt-.': 'custom:insert-plain-closing-angle'
```
3. Restart Atom

Now you can press `alt-.` to insert a plain `>` without triggering the autoclose behavior.

**Comment by pdxwolfy** [comment]
Very nice. Thanks, Ben!
