### ISSUE TITLE
Adds a ' /' after a empty tag.

### ISSUE THREAD

**Issue by XuanQuan** [mattberkowitz/autoclose-html#185]
*I'm a bit new to GitHub and never reported a bug before so sorry if this was already resolved*

When I try to close a empty tag such as `<br>`, the result is `<br />`, I'm pretty sure the program is just trying to close an empty tag when in reality there isn't suppose to be one.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28849427/27290049-d6004464-54c0-11e7-9b3f-ec45f4b0c2c3.gif)

**Comment by mattberkowitz** [comment]
There's an option `Make Never Close Elements Self-Closing` you can turn off to disable this. Alternately, you can define a custom set of `Never Close Elements` without `br` to only disable it for that element
