### ISSUE TITLE
feature and bug

### ISSUE THREAD

**Issue by Vic-ST** [mattberkowitz/autoclose-html#188]
could you add that p tags are inline so instead of this:

```
<p>
text
</p>
```
this:

```
<p>text</p>
```

also, when I write ```<br/>``` it also adds ```</br>```.

**Comment by 0xLeathery** [comment]
I think you're after the settings. This doesn't look like a bug. See below for my config

![image](https://user-images.githubusercontent.com/23321960/29645398-3ef3a47c-88d1-11e7-8d1f-1102822de23d.png)

**Comment by Vic-ST** [comment]
Oh sorry! I didn't see that.
