### ISSUE TITLE
Make Never Close Elements Self Closing function

### ISSUE THREAD

**Issue by lucierabahi** [mattberkowitz/autoclose-html#213]
Hi,

The "Make Never Close Elements Self Closing function" isn't working (anymore, and I have no idea why it stopped...).

I type `br` and would like `<br />` to appear but I still have `<br>`. 

The function is enabled in the settings and `br` is listed in "Never Close Elements".

I suspect issues between various packages downloaded, as the [https://atom.io/packages/comment](url)  didn't work either (I uninstalled it since, Those are the two only packages I downloaded that didn't work). 

Any advice?

**Comment by binaryfunt** [comment]
Hi @lucierabahi , it seems this package is no longer being maintained. Feel free to check out [autoclose-html-plus](https://atom.io/packages/autoclose-html-plus), a fork of this package which is actively being maintained.

P.S., in Atom, you can insert comments using <kbd>Ctrl</kbd>+<kbd>/</kbd>

**Comment by lucierabahi** [comment]
Thank you. It was my first steps with coding and GitHub ^^.
