### ISSUE TITLE
Autoclosing tag when enter > char beetween curly brackets

### ISSUE THREAD

**Issue by kziajor** [mattberkowitz/autoclose-html#29]
When I try to use Laravel Blade and try to enter variable inside opened tag then it close automatically. Example:
When try to write something like this:
<div class="{{{ $some->variable }}}"></div>

I get:
<div class="{{{ $some->
	
</div> }}}"

When try to write:
<h1>{{{ $some->varialbe }}}</h1>

I get:
<h1>{{{ $user-></h1>}}}</h1>

Because every time when i pressed ">" char then program looks for first occurrence of open tag to the left and if it finds it then it inserts closing tag even if it actually exists.

**Comment by mattberkowitz** [comment]
`<h{{importance}}>` should not break with 0.15, it tabs weirdly but I think that's an atom autotabbing issue.
