### ISSUE TITLE
Add option for allowing all tags to be inline

### ISSUE THREAD

**Issue by Flynsarmy** [mattberkowitz/autoclose-html#3]
Add a * option to allow all elements show inline.

**Comment by PCateNumbersUSA** [comment]
Would love the see similar options as well.

**Comment by mbugbee** [comment]
Any movement on this?

**Comment by davidspiess** [comment]
I would appreciate it too. I'm so used to it from sublime.

**Comment by mattberkowitz** [comment]
With 0.20.0 you can use "*" for the Force Inline option to accomplish this.
