### ISSUE TITLE
Add support based on file extension, rather than file type.

### ISSUE THREAD

**Issue by laszlof** [mattberkowitz/autoclose-html#32]
This plugin would probably be a bit more useful if it could be used in multiple file types. I'm sure theres a number of people who write HTML within PHP files, or one of the various template systems available, and could use the auto-complete feature. I personally use Handlebars templates and could make use of it if it was available.

I think adding an option to the config to allow any file extension to be handled would be useful.

**Comment by apeacox** [comment]
:+1:

**Comment by seanosaur** [comment]
I was having the same problem with Rails ERB files and so did a quick look and found that when I added 'HTML (Ruby - ERB)' to the grammars section, it works fine for me. If @mattberkowitz is up for it, I could do a PR that adds this functionality and include any other "grammars" that are requested.

**Comment by mattberkowitz** [comment]
Sure, feel free to submit. I've gotten a report of some more depreciation warnings so I will probably try and squeeze out a new release sometime soonish.

I'm super busy right now and haven't had too much time to devote to working on this plugin, although putting in support based on file type is the highest thing on my list. Doing it by grammar just seems to confusing to someone just trying to jump into atom and just wanting the plugin to work in their preferred templating language

**Comment by seanosaur** [comment]
Is there a cleaner or better way to do it than what I did?


Here's all I did, not sure if it's the correct way 

Was:

    17    grammars: ['HTML']

    42    @grammars = ['HTML'].concat(value.split(concatPattern))

Is: 

    17    grammars: ['HTML', 'HTML (Go)', 'HTML (Rails)', 'HTML (Mustache)', 'HTML (Ruby - ERB)', 'PHP']

    42    @grammars = ['HTML', 'HTML (Go)', 'HTML (Rails)', 'HTML (Mustache)', 'HTML (Ruby - ERB)', 'PHP'].concat(value.split(concatPattern))

**Comment by mattberkowitz** [comment]
That's fine. We could declare a `defaultGrammars = []` up by the tag regexs and then use that in both instances, that's the only real optimization I see
