### ISSUE TITLE
improving the autocomplete

### ISSUE THREAD

**Issue by thewhitetulip** [mattberkowitz/autoclose-html#36]
While working with Bootstrap3 we need to add a lot of divs with a lot of classes so it would be great if a this would be an option, `div.hello` would be expanded to `<div class="hello"></div>`, would save a lot of time

**Comment by mattberkowitz** [comment]
While I can certainly see the usefulness of this, in your case, It seems better suited for it's own plugin.

**Comment by thewhitetulip** [comment]
Valid point :+1: Actually I was pondering about it, maybe when I have time in the future I'll fork your repo and  modify to suit my purpose :)

**Comment by thewhitetulip** [comment]
There is a plugin for that actually, https://atom.io/packages/emmet, works like a charm
