### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jcgallaher** [mattberkowitz/autoclose-html#37]
I've been getting a error about atom.workspaceView is no longer available. On line 108 in lib/autoclose-html.coffee is where it takes me to. I'd fix it myself if I was certain enough how to without breaking stuff.

See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Jim\AppData\Local\atom\app-0.174.0\resources\app\src\atom.js:55:11)
Object._events (c:\Users\Jim\.atom\packages\autoclose-html\lib\autoclose-html.coffee:108:13)
```

**Comment by mattberkowitz** [comment]
I'll take a look at it, seems like they've updated the API

**Comment by jcgallaher** [comment]
Yeah they've changed some stuff. Even for templates too.

**Comment by stramel** [comment]
:+1:

**Comment by mattberkowitz** [comment]
0.14.0 should fix

**Comment by jcgallaher** [comment]
It's fixed. I confirm it. Thank you sir!
