### ISSUE TITLE
Cannot read property getBufferPosition of undefined

### ISSUE THREAD

**Issue by LM450N** [mattberkowitz/autoclose-html#46]
This issue is resolved in fact but I wanted to keep a trace on the repo because I lost few minutes to find a solution and it was pretty simple.

When I updated the autoclose-html package, I was got everytime the following error.
## Error ##

I had an error when I'm finishing to write an opening HTML tag.
I mean I write `<div`, it's ok but when I type `>` the error is occurring.
But the tag is closed.

![autoclose-html-error](https://cloud.githubusercontent.com/assets/2325091/5872875/74e37be4-a2f0-11e4-8c94-f849d2155a94.png)

## Solution ##

Close then restart Atom does nothing.
Indeed, you have to disable and re-enable the package autoclose-html.
That's all.

**Comment by mattberkowitz** [comment]
Seems like this is something with bracket-matcher. Bracket-matcher binds a function to execute before any editor.insertText call, so when autoclose-html was trying to insert the closing text it fired. For some reason it had a null reference, but I don't think it was related to autoclose-html. Perhaps the installation of  a new plugin caused to to lose a reference for some reason. 

I'm going to keep this open, in case others have a similar problem after upgrading and can add any insight, but I don't think there's anything to be done on my end that can correct this error.
