### ISSUE TITLE
stylesheets is deprecated

### ISSUE THREAD

**Issue by aparedes** [mattberkowitz/autoclose-html#47]
Just a small deprecation issue. :D
![stylesheets](https://cloud.githubusercontent.com/assets/480605/5877357/461a44b2-a31f-11e4-9834-63b1b5ebbb67.png)

**Comment by mattberkowitz** [comment]
Thanks, I don't get that warning for some reason. I'll update in my next version

**Comment by aparedes** [comment]
You can only see it when in developer mode.

**Comment by mattberkowitz** [comment]
Fixed in 0.15
