### ISSUE TITLE
 Closing ERb tags

### ISSUE THREAD

**Issue by vblumen** [mattberkowitz/autoclose-html#57]
I wanted to customize the tool to autoclose my ERb HTML tags. Is there a way to make it do this?: as soon as I enter "<%" the tool closes it with " %>"  putting a space in between and leaving the cursor right behind the first "%" sign so I can add "=" if need be. I'm pretty sure this is an easy fix for an experienced programer, but I don't know how to do it.

**Comment by mattberkowitz** [comment]
If atom is adding `%>` after you type `<%` then it's another plugin that is doing it. This plugin only adds `</...>`  after `<...>` is entered.

**Comment by yakschuss** [comment]
He wants the functionality, does it exist anywhere? I also want to auto-close my ERB HTML tags.
