### ISSUE TITLE
Doesn't work for PHP files

### ISSUE THREAD

**Issue by SolusSoftworks** [mattberkowitz/autoclose-html#58]
Most (if not all) of my non-conceptual HTML is in PHP files rather than HTML but this plugin doesn't seem to work for PHP files. :(

**Comment by mattberkowitz** [comment]
If you add PHP to the Additional Grammars options, it should work. Alternately you can use * to enable across the board

**Comment by SolusSoftworks** [comment]
Ah that makes sense. Didn't know what that option was for but I figured there would be a way to do it. I was looking for a 'Filetypes:' field... Thanks.

**Comment by fseminario** [comment]
Yeah I agree with Solus. I didnt know what that was for. Maybe a grayed out example of choices would be helpful to prevent for future issues. Thanks!
