### ISSUE TITLE
Autoclose-HTML Throws Deprecation Cop Warning

### ISSUE THREAD

**Issue by mattlovaglio** [mattberkowitz/autoclose-html#59]
The package seems to generate a strange error since the last update. It triggers a deprecation cop warning that associates the error with the Atom Core. I opened a previous ticket with the Atom. You can reference the thread here: https://github.com/atom/atom/issues/6278

I'm on and running: 
MacBook Pro Retina
OS X Yosemite 10.10.2
Atom Version 0.189.0 (0.189.0)

Here's a screenshot of the Deprecation Cop error.

![deprecation cop - atom](https://cloud.githubusercontent.com/assets/10821303/7031892/e60adc0a-dd3c-11e4-909b-d1558a0e3a98.jpeg)

**Comment by mattberkowitz** [comment]
I've more or less done this but there were issues with the default values causing config items to disappear entirely, if that issue has been resolved then I'll merge in the branch otherwise I need to make a few more edits first
