### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by ChristianGrech** [mattberkowitz/autoclose-html#65]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (C:\Users\Christian\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:247:11)
Package.activateNow (C:\Users\Christian\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:218:14)
<unknown> (C:\Users\Christian\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30)
Package.measure (C:\Users\Christian\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
```

**Comment by stramel** [comment]
+1

**Comment by willl** [comment]
Looking at autoclose-html.coffee, the required changes for this package is to change the [configDefaults](https://github.com/mattberkowitz/autoclose-html/blob/549061b078e6a68725af3c18fbdf723699efcb7b/lib/autoclose-html.coffee#L7) (and related) sections into using the newer config schema as defined in that link to the Config API.
