### ISSUE TITLE
double tag closing

### ISSUE THREAD

**Issue by silverspectro** [mattberkowitz/autoclose-html#69]
when auto-closing, the closing tag appear two times

ex : 

<div></div></div>

**Comment by mattberkowitz** [comment]
I've found a way to replicate this if I have the same document open twice (in multiple pane mode) does this seem like what might have happened to you, or does this bug occur all the time?

**Comment by silverspectro** [comment]
Yes it was that !
The bug only seems to happen this way.

thanks !

**Comment by CodeTriangle** [comment]
I am having the same problem ever since I updated to the newest version.

**Comment by peirix** [comment]
@CodeTriangle I had the same issue after updating, but it dissapeared after restarting Atom.

**Comment by mattberkowitz** [comment]
I just published v.0.18.0, it should solve the double completion due to having a document open in multiple tabs
