### ISSUE TITLE
Doesn't close anymore when attributes in tag

### ISSUE THREAD

**Issue by doncx** [mattberkowitz/autoclose-html#70]
This plugin has worked well until last week when suddenly adding attributes to a tag causes it not to close.

For instance, "&lt;div&gt;" closes just fine but "&lt;div class="myclass"&gt;" doesn't close.

What happened?  I've disabled all the autocomplete packages and that makes no difference.

Version 0.16.2 on Atom 0.201.0

Thanks for any suggestions.

**Comment by mattberkowitz** [comment]
I'll take a look at it, thanks for reporting

**Comment by mattberkowitz** [comment]
I've just published 0.17.0 to fix this. Thanks for letting me know!

**Comment by doncx** [comment]
Quality of Life++

Thanks, Matt!
