### ISSUE TITLE
Does Not Activate In HTML (Angular) Grammar

### ISSUE THREAD

**Issue by eviljoe** [mattberkowitz/autoclose-html#71]
The HTML auto-closing does not work when your current editor's grammar is set to "HTML (Angular)."

To Recreate:
 1. Open some HTML
 1. Open the grammar selector (default hotkey `ctrl+shift+L`)
 1. Select the "HTML (Angular)" grammar
  * Once this grammar is selected, auto-closing will no longer work util the grammar is switched back to "HTML."

**Comment by mattberkowitz** [comment]
There is a setting to add Additional Grammars, just add it there for now. I'll add it to the default list in the future

**Comment by eviljoe** [comment]
Whoops, sorry about that.  Thanks for the quick response!
