### ISSUE TITLE
Adding 'div' to force-inline option creates two close div tags

### ISSUE THREAD

**Issue by jasonku09** [mattberkowitz/autoclose-html#73]
Typing <div> results in <div></div></div>

**Comment by mattberkowitz** [comment]
I'm not able to replicate this issue. I've noticed some reports of double closing tags being related to when the plugin updates versions. Can you try fully closing atom and reopening it, do you still get double closing tags?

**Comment by jasonku09** [comment]
Ah closing and reopening did the trick. Thanks!
