### ISSUE TITLE
Typing a `<` in a tag's attribute closes the tag

### ISSUE THREAD

**Issue by davidlukerice** [mattberkowitz/autoclose-html#74]
I've been using the less than (`<`) character in some angular expressions in some of the tag attributes, but typing it closes off the current tag. For example, when I'm trying to type
``` html
<div ng-if="model.value > 0 "></div>
```
and add the `<`, the div tag tries to close, creating
``` html
<div ng-if="model.value ></div>"
```
instead of
``` html
<div ng-if="model.value >"
```

**Comment by mattberkowitz** [comment]
I'll work on modifying my algorithm to work for this case, I'll rely here when I've cut a new build that fixes it

**Comment by mattberkowitz** [comment]
I added this awhile back but never closed the issue ;)
