### ISSUE TITLE
Spacebars support

### ISSUE THREAD

**Issue by nathanhornby** [mattberkowitz/autoclose-html#75]
Hi there,

How would I go about adding Spacebars support? I don't really need any extra functionality, just for the file type to be included in the autoclose list.

Cheers,

Nathan

**Comment by mattberkowitz** [comment]
I'm looking for a good/better way to handle user defined file types. For now there is a setting "Additional Grammars" that takes a comma delimited list of grammar names. The grammar name is located in the bottom right-hand corner of the atom window

**Comment by nathanhornby** [comment]
Awesome, thanks!
