### ISSUE TITLE
Multiple cursors add duplicate closing tabs on the wrong lines

### ISSUE THREAD

**Issue by raulsntos** [mattberkowitz/autoclose-html#76]
**Atom version:** 1.0.0
**OS:** Windows 8.1

Having the following code with a cursor at the end of each line:
```html
<h1
<h2
<h3
```
When typing ">" it closes the tags like this:
```html
<h1></h2></h1></h1>
<h2></h3></h2></h1>
<h3></h3></h1>
```

**Comment by jidan70** [comment]
I have this probleme too.
it adds tags at the begining of my code even if i am at the end of my code, when i close a tag.

**Comment by andreldm** [comment]
I also face this problem in this scenario with multiple cursors:

    <li item1
    <li item 2
    <li item 3

When '>' is pressed,  this is the result:

    <li>
      
      
      
    </li>
    </li>
    </li>item 1
    <li>
      
    </li>item 2
    <li>
      
    </li>item 3

I guess the auto closing behavior should be disabled when multiple cursors are in use.

**Comment by mattberkowitz** [comment]
With 0.22.0 I changed the method of detecting the end of a tag, which made this a bit better. however you lose the multiple cursors, which isn't perfect, I'll refine it a bit more in future releases

**Comment by andreldm** [comment]
Thanks, it's now working properly.
