### ISSUE TITLE
atom autoclose-html issue

### ISSUE THREAD

**Issue by mladarsh** [mattberkowitz/autoclose-html#79]
Two closing tags appear for some reason. 
If i say \<h1>
i get \<h1>\</h1>\</h1>
but i should actually get \<h1>\</h1>

**Comment by jhartman86** [comment]
I'll confirm, seeing this as well w/ version 0.18.0

**Comment by mattberkowitz** [comment]
@jhartman86 @mladarsh I've noticed it seems to happen after an upgrade. If you restart atom is the issue still occuring?
