### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by Cephel** [mattberkowitz/autoclose-html#85]
I have no idea how to even report this issue, it's as if the package isn't even installed (but it is).

Video for reference: [Link](https://my.mixtape.moe/yxvkek.webm).

**Comment by mattberkowitz** [comment]
It seems like often the plugin doesn't work immediately after being installed. If you restart atom does it start working?

**Comment by Cephel** [comment]
Nope, that does not solve the problem.

**Comment by aspushkinus** [comment]
Same problem here.

**Comment by d3ngar** [comment]
Same issue.

**Comment by aspushkinus** [comment]
The restart solved the problem for me. I did reset the Atom configuration to default though (deleted ~/.atom directory).

**Comment by mattberkowitz** [comment]
Some questions for you guys:
1) Platform/Atom version
2) Did you use this plugin prior to Atom 1.x? Did you just upgrade to 1.x? If not, did the plugin work in previous 1.x versions?

**Comment by Cephel** [comment]
1) Windows / Latest
2) No. No, been using it for a while. And no, I never recall it ever working, but I didn't think of reporting the issues back then, because I was in a state where I tested out various Text editors and configurations.

**Comment by aspushkinus** [comment]
1) Mac OS X latest
2) I blew away my Atom configs before I upgraded to the latest version.

BTW, the auto-close still doesn't always work for me. It only works when the document I'm editing is a full HTML that starts with <html> at the top. When I try to edit an angular view (a partial HTML) it doesn't work. I put both files into the same directory.

I have the following code in my angular view:

```html
<h3>{{product.name}}</h3>

<em class="pull-right"></em>
```

**Comment by mattberkowitz** [comment]
@aspushkinus You probably need to add whatever the Grammar is for Angular uses to the Additional Gramamrs option.


Per README.md:

"By Default works for HTML, HTML (Go), HTML (Rails), HTML (Mustache), HTML (Ruby - ERB), PHP"

and

"Additional Grammar

Comma delimited list of grammar names, other than HTML and PHP, to apply this plugin to. Use "*" to run for all grammars."

**Comment by aspushkinus** [comment]
@mattberkowitz Angular doesn't use any special grammar for HTML. My snippet of code above is clean and pure HTML. When I try to add a <p> tag at the bottom - it doesn't auto-close. When I do that in the full HTML document - it works.

**Comment by Delimitless** [comment]
@aspushkinus Do you have angularjs package installed in atom? I had this same issue in all my partials until I disabled that package and restarted. Seems they conflict with one another. Though obviously having to disable it isn't ideal.

**Comment by aspushkinus** [comment]
@Delimitless This was exactly it. As soon as I disabled AngularJS package the problem with auto-close went away. Oh well, I like auto-close, but I kinds need my AngularJS tools too...

**Comment by Cephel** [comment]
I think I found the reason for this behavior too.

As you can see in this screenshot:
![](http://i.imgur.com/Rcuw4MV.png)
The AngularJS package adds its own HTML grammar, which might not be supported at all, despite not actually being different from regular HTML syntax.

**Comment by mattberkowitz** [comment]
@Cephel Yep that's what I suspected. I just published 0.19.0 which includes the HTML (Angular) grammar as a default. Once someone verifies that this fixes the issue I'll close this topic

**Comment by Delimitless** [comment]
Nice find @Cephel and thanks @mattberkowitz that fixed it! Cheers

**Comment by Cephel** [comment]
Confirming the fix works. Nicely done.

Complementary [video](https://my.mixtape.moe/olzjii.webm)
