### ISSUE TITLE
JSX closing tags added twice

### ISSUE THREAD

**Issue by peduxe** [mattberkowitz/autoclose-html#86]
Currently it works with .jsx files although it adds the closing tags twice.

```html
<div>
```

to:
```html
<div>

</div>
</div>
```

**Comment by mattberkowitz** [comment]
Did you just upgrade to 0.19.0 that I published? If so, try restarting Atom. I think there's a bug where an upgrade causes to plugin to execute an event twice until Atom has been restarted.

**Comment by peduxe** [comment]
@mattberkowitz you were right, kinda strange...
