### ISSUE TITLE
Duplicate closing tags.

### ISSUE THREAD

**Issue by InsomniaNoir** [mattberkowitz/autoclose-html#88]
I just downloaded the recent update, 0.19.0, and I'm running into an issue where the tags are closing automatically as they should but the closing tags get duplicated on autocomplete.  Rather than getting the following.

```
<div class="col-md-4">
</div>
```

I continually get something like this:

```
<div class="col-md-4">
</div>
</div>
```

**Comment by mattberkowitz** [comment]
It's a known bug, just restart atom and it will go away
