### ISSUE TITLE
Two ending tags added when "Close on End of Opening Tag" checked

### ISSUE THREAD

**Issue by olivierlacan** [mattberkowitz/autoclose-html#9]
![bug-atom-autoclose-html](https://f.cloud.github.com/assets/65950/2429520/353b9126-ac87-11e3-86aa-a0f978ae6205.gif)

Using 0.5.0 with Atom 0.73.0

**Comment by dushaunac** [comment]
Hi There,

Using Atom 1.0.2 with autoclose-html 0.18.0 and I've suddenly come across the doubling up again. Was the Error truly fixed?

![screen shot 2015-07-23 at 15 13 50](https://cloud.githubusercontent.com/assets/6787759/8852489/7e85a38e-314d-11e5-8c80-ed61e49f8c58.png)
