### ISSUE TITLE
Extra closing tag being created

### ISSUE THREAD

**Issue by Walter-0** [mattberkowitz/autoclose-html#91]
If I type `<p>` I expect 
```
<p>

</p>
```
Instead I get 
```
<p>
</p>
</p>
```

**Comment by mattberkowitz** [comment]
Thanks for reporting, I've gotten tons of these already :) Gonna leave this open in hopes of stopping further reports, but I doubt it will.

**Comment by mattberkowitz** [comment]
PS. To fix, just restart Atom and it will go away. It's related to events getting double bound after a version upgrade

**Comment by bott17** [comment]
@mattberkowitz  restart Atom works fine! :P
