### ISSUE TITLE
Just updated and now getting a "double" closing tag.

### ISSUE THREAD

**Issue by cthomas1489** [mattberkowitz/autoclose-html#92]
I just updated the package and now the auto close doubles itself.

ie. I type <html> and when I finish that class ' >' it writes </html></html> below it.

![screen shot 2015-09-09 at 2 16 29 pm](https://cloud.githubusercontent.com/assets/5324570/9771702/64192c98-56fd-11e5-8d70-f881f61c3ab0.png)

**Comment by mattberkowitz** [comment]
Yep, it's a bug, restart atom to fix it for now
