### ISSUE TITLE
Should not autoclose when issuing an undo command

### ISSUE THREAD

**Issue by JordanMajd** [mattberkowitz/autoclose-html#94]
I had an issue where I was trying to undo 
```html
<a</a>
```
to 
```html
<a></a>
````
but it autofills to
```html
<a></a></a>
```

I am able to reproduce this by typing `<a>` then allowing autoclose to close it to `<a></a>` then if you delete the `>` from `<a>` you get `<a</a>`. Next hit `ctrl+z` and you will get `<a></a></a>`. Repeatedly hitting `ctrl+z` will repeatedly add additional `</a>`s

At one point I had somehow it a loop where I would `ctrl+z` and it would change `<a</a>` to `<a>` and then back to `<a</a>` almost instantly. I am unable to reproduce this issue though but I assume it is related.

**Comment by ludberg** [comment]
I have a similar problem where i can't undo tags like <br />.. As soon as I remove /> it autocloses the br-tag.

**Comment by mattberkowitz** [comment]
With 0.22.0 I changed the method of detecting the end of a tag, which should have resolved this issue as well
