### ISSUE TITLE
doing find-and-replace, code disappeared

### ISSUE THREAD

**Issue by hd132605** [mattberkowitz/autoclose-html#96]
with autoclose-html on, this problem occured.
first, type this.

```html
&lt;div class=&gt;
```

and find '&lt' and replace to '<'.
then
```html
<div class=&gt;
```

then find 'gt;' and replace to '>'

code disappeared!

with autoclose-html package off, this not occured.

**Comment by mattberkowitz** [comment]
With 0.22.0 I changed the method of detecting the end of a tag, which should have resolved this issue as well
